"""add Review model to reviews app

Revision ID: 31af50cfdace
Revises: c30a3b1de403
Create Date: 2024-08-21 19:19:43.514551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '31af50cfdace'
down_revision: Union[str, None] = 'c30a3b1de403'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('datetime_created', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('datetime_updated', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('author_uid', sa.UUID(), nullable=False),
    sa.Column('blog_uid', sa.UUID(), nullable=False),
    sa.CheckConstraint('rating <= 5', name='check_rating_max'),
    sa.CheckConstraint('rating >= 1', name='check_rating_min'),
    sa.ForeignKeyConstraint(['author_uid'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['blog_uid'], ['blogs.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_reviews_uid'), 'reviews', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_uid'), table_name='reviews')
    op.drop_table('reviews')
    # ### end Alembic commands ###
