"""add Tag and BlogTag model to tags app

Revision ID: 3c01e8959817
Revises: 31af50cfdace
Create Date: 2024-08-22 01:38:05.004749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c01e8959817'
down_revision: Union[str, None] = '31af50cfdace'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('datetime_created', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('datetime_updated', postgresql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_tags_uid'), 'tags', ['uid'], unique=False)
    op.create_table('blog_tags',
    sa.Column('blog_uid', sa.UUID(), nullable=False),
    sa.Column('tag_uid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['blog_uid'], ['blogs.uid'], ),
    sa.ForeignKeyConstraint(['tag_uid'], ['tags.uid'], ),
    sa.PrimaryKeyConstraint('blog_uid', 'tag_uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog_tags')
    op.drop_index(op.f('ix_tags_uid'), table_name='tags')
    op.drop_table('tags')
    # ### end Alembic commands ###
