"""add Blog model to blog app

Revision ID: c30a3b1de403
Revises: 7276109b97c5
Create Date: 2024-08-20 21:01:03.141497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c30a3b1de403'
down_revision: Union[str, None] = '7276109b97c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogs',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('publish_date', sa.Date(), nullable=True),
    sa.Column('datetime_created', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('datetime_updated', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('author_uid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['author_uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_blogs_uid'), 'blogs', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blogs_uid'), table_name='blogs')
    op.drop_table('blogs')
    # ### end Alembic commands ###
